version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres-attendance
    ports:
      - "6567:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: attendance_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: backend-attendance
    ports:
      - "3010:3010"
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: attendance_db
      PORT: 3010
    restart: unless-stopped

  employee-attendance:
    build: ./Employee-attendance
    container_name: employee-attendance
    ports:
      - "8069:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3010
    restart: unless-stopped

  hr-attendance:
    build: ./HR-attendance
    container_name: hr-attendance
    ports:
      - "8070:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:3010
    restart: unless-stopped

volumes:
  pgdata:

